### ISSUE TITLE
Maybe translate integration test to C++

### ISSUE THREAD

**Issue by tomsmeding** [summitto/pgp-key-generation#15]
We had a discussion about translating the integration tests, which I had written in Python before, to C++.

Arguments for this translation include:
- Reduction in the number of dependencies
- Reduction in the amount of knowledge needed for contributing to the project

Arguments against this translation include:
- While using Python does not make it _significantly_ easier on any front to write the tests (as far as I can see), it does reduce the amount of effort needed, because of the higher-level language.
- Python is not a particularly difficult language.
- Using Python for tests is fairly usual.

Please add more arguments to these lists if they appear.

**Comment by rockhouse** [comment]
No need, python tests are fine.
